### ISSUE TITLE
Presence of a user avatar in a scene

### ISSUE THREAD

**Issue by micfio** [antpb/three-object-viewer#50]
Hello,Is possibile to use an avatar for the presence of a user in a scene? How work the spawning point?
Thanks in advances

**Comment by antpb** [comment]
Hello @micfio ! We are working on a third person character controller and will definitely have the option for you to define your avatar in the near future. I'll update this issue when it launches.

As for the Spawn Point block when you add a 3D Environment Block to your post, a spawn point will be automatically added. The spawn point only serves the purpose of setting the initial load position for a player entering a 3D Environment. If you hit the 'R' key the player will respawn at the spawn point location as well.

**Comment by antpb** [comment]
Hi there @micfio ! Just wanted to let you know that the latest version of 3OV has included Avatars. you can see a preview of it here: https://www.youtube.com/watch?v=c_-hMbGGWgY

Going to close this now that it exists. thanks!
